export const FETCH_RESERVATION_REQUEST = "FETCH_RESERVATION_REQUEST";
export const FETCH_RESERVATION_FAILURE = "FETCH_RESERVATION_FAILURE";
export const FETCH_RESERVATION_SUCCESS = "FETCH_RESERVATION_SUCCESS";

export const POST_CART_REQUEST = "POST_CART_REQUEST";
export const POST_CART_FAILURE = "POST_CART_FAILURE";
export const POST_CART_SUCCESS = "POST_CART_SUCCESS";
